import {getLanguage,setLanguage,translate,localize} from './i18n.js';
import {sources,techniques,terms,concepts,examples,fingers,numerals,lessons,phrases,questions,questionMap,describe} from './data.js';
import {STORAGE_KEY,emptyState,validateState,mergeState,stats,recommendation,makeSession,record} from './learning.js';
import {esc,icon,glyph,qinDiagram,anatomy,sourceLinks} from './ui.js';
let state=emptyState(),storageProblem='',storageBlocked=false;
try{const raw=localStorage.getItem(STORAGE_KEY);if(raw)state=validateState(JSON.parse(raw));}catch{storageProblem='无法读取已有进度。原记录未覆盖；可先导出原始记录，再导入有效备份。';storageBlocked=true;}
let activePart='left',explorerIndex=0,lessonStep=0,termFilter='全部',query='',phraseIndex=0,noteIndex=0,phraseStudy=true,phraseReveal=false,session=null,noticeTimer,importCandidate=null;
const app=document.querySelector('#app');
const lessonById=id=>lessons.find(l=>l.id===id)||lessons[0];
function toast(message){const el=document.querySelector('#notice');el.textContent=message;localize(el);el.classList.add('visible');clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>el.classList.remove('visible'),5000);}
function save(overwrite=false){if(storageBlocked)return;try{const raw=localStorage.getItem(STORAGE_KEY);if(raw&&!overwrite){const merged=mergeState(state,validateState(JSON.parse(raw)));state={...state,attempts:merged.attempts,completed:merged.completed};}localStorage.setItem(STORAGE_KEY,JSON.stringify(state));storageProblem='';}catch{storageProblem='浏览器无法保存进度。当前练习仍可继续，请在「设置」中导出备份。';toast(storageProblem);}}
function route(){return location.hash.slice(1).split('/');}
function navigate(to){if(location.hash==='#'+to)render();else location.hash=to;}
const btn=(text,action,value='',className='button')=>`<button class="${className}" data-action="${action}" data-value="${esc(value)}">${text}</button>`;
const link=(text,to,className='button')=>`<a class="${className}" href="#${to}">${text}</a>`;
function topHeading(eyebrow,title,text=''){return `<div class="page-heading"><p class="eyebrow">${eyebrow}</p><h1>${title}</h1>${text?`<p class="lede">${text}</p>`:''}</div>`;}
function languageButton(){return `<button class="text-button language-toggle" data-action="language" aria-label="${getLanguage()==='en'?'切换到中文':'切换到英文'}">${getLanguage()==='en'?'中文':'English'}</button>`;}
function shell(content,tab){const nav=[['home','今日','home'],['learn','课程','learn'],['practice','练习','practice'],['explore','字典','explore'],['progress','进度','progress']];return `<aside class="sidebar"><a class="brand" href="#home"><span class="seal">琴<br>读</span><span>琴读<small>GUQIN READER</small></span></a><p class="sidebar-caption">读谱，也是一种练习。</p><nav aria-label="主导航">${nav.map(([id,label,ic])=>`<a href="#${id}" class="nav-link ${tab===id?'active':''}" ${tab===id?'aria-current="page"':''}>${icon(ic)}<span>${label}</span>${tab===id?'<span class="nav-dot"></span>':''}</a>`).join('')}</nav><div class="sidebar-bottom"><p>一字一音<br>循序渐进</p><a href="#settings">${icon('settings')} 设置与备份</a><a href="#sources">资料与方法 ↗</a><span class="local-label"><i></i> 进度仅存于此浏览器</span></div></aside><div class="workspace"><header class="topbar"><a href="#home" class="mobile-brand">琴读 <span>GUQIN READER</span></a><span class="breadcrumb">减字谱学习手记 <span>/</span> ${nav.find(n=>n[0]===tab)?.[1]||'读谱伴侣'}</span><div class="top-actions">${languageButton()}${btn(state.support?'辅助已开':'辅助','support','','text-button')}<a href="#settings" aria-label="设置与备份" class="settings-link">${icon('settings')}</a></div></header>${storageProblem?`<div class="storage-warning" role="alert">${esc(storageProblem)} <a href="#settings">备份与恢复</a></div>`:''}<main id="main" tabindex="-1">${content}</main><footer>琴读 · 为你的古琴课，留一点课后的练习。<a href="#sources">参考资料</a></footer></div><nav class="mobile-nav" aria-label="移动导航">${nav.map(([id,label,ic])=>`<a href="#${id}" class="${tab===id?'active':''}" ${tab===id?'aria-current="page"':''}>${icon(ic)}<span>${label}</span></a>`).join('')}</nav>`;}
function home(){const all=stats(state),rec=recommendation(state),l=lessonById(rec.lesson),due=Object.values(all).filter(s=>s.dueNow).length,ind=state.attempts.filter(a=>!a.assisted),correct=ind.filter(a=>a.correct).length;const demo=examples[0];return `${topHeading('你的读谱时光 · A LITTLE, OFTEN','读懂一字，<br>奏出一声。','把复杂的谱字，慢慢读成指尖熟悉的动作。')}<section class="home-grid"><div class="hero-notation panel"><div class="panel-top"><span class="small-label">今日一字</span><span class="badge">按音</span></div><a href="#explore" class="hero-symbol" aria-label="拆解今日谱字：名九勾五">${glyph(demo.code,'名九勾五')}<span class="vertical-note">由字入琴</span></a><div class="hero-caption"><h2>名九勾五</h2><p>左手名指 · 九徽 · 右手勾 · 五弦</p></div><a class="quiet-link" href="#explore">拆开看看 ${icon('arrow')}</a></div><div class="daily-stack"><section class="daily-card"><span class="eyebrow">接下来，学一点</span><div class="daily-number">${rec.type==='review'?'温故':'知新'}<span>${rec.type==='review'?'REVISIT':'NEXT LESSON'}</span></div><h2>${rec.type==='review'?concepts[rec.concept]:l.title}</h2><p>${rec.reason}</p>${rec.type==='review'?btn(`开始针对练习 ${icon('arrow')}`,'start-concept',rec.concept,'button primary'):link(`开始这一课 ${icon('arrow')}`,`learn/${l.id}`,'button primary')}<span class="caption">${rec.type==='review'?'独立回忆 · 即时反馈':`${l.time} · 一个示例，再试一试`}</span></section><div class="stats-strip"><div><strong>${state.completed.length}<small> / 6</small></strong><span>已读课程</span></div><div><strong>${due}</strong><span>待复习概念</span></div><div><strong>${ind.length?Math.round(correct/ind.length*100)+'%':'—'}</strong><span>独立答对率</span></div></div></div></section><section class="section"><div class="section-title"><div><span class="eyebrow">LEARNING PATH</span><h2>从字，到句</h2></div><a href="#learn" class="quiet-link">全部课程 ${icon('arrow')}</a></div><div class="lesson-preview">${lessons.slice(0,3).map(x=>lessonCard(x,true)).join('')}</div></section><a class="phrase-banner" href="#phrases"><span class="banner-icon">句</span><div><span class="small-label">带着前文，继续读</span><h3>读一小段，让谱字连起来。</h3><p>三组原创短句 · 可切换自测模式</p></div>${icon('arrow')}</a>`;}
function lessonCard(l,compact=false){return `<a href="#learn/${l.id}" class="lesson-card ${compact?'compact':''}"><span class="lesson-number">${l.number}</span><div><span class="small-label">${l.time}${state.completed.includes(l.id)?' · 已读':''}</span><h3>${l.title}</h3><p>${l.subtitle}</p></div>${state.completed.includes(l.id)?icon('check'):icon('arrow')}</a>`;}
function learn(id){if(!id)return `${topHeading('六堂小课 · THE FOUNDATIONS','循序读谱','可从头学习，也可直接进入老师课上遇到的内容。')}<div class="lesson-list">${lessons.map(l=>lessonCard(l)).join('')}</div><aside class="tip-box">${icon('leaf')}<p>课程已读不等于熟练。独立答题表现会决定你的复习建议；课程始终可以自由访问。</p></aside>`;const l=lessonById(id),e=examples.find(e=>e.id===l.example),step=l.steps[Math.min(lessonStep,2)];return `<a href="#learn" class="quiet-link back-link">${icon('back')} 课程目录</a>${topHeading(`第 ${l.number} 课 · ${l.time}`,l.title,l.subtitle)}<div class="lesson-workspace"><section class="panel lesson-copy"><div class="step-tabs" aria-label="学习步骤">${l.steps.map((s,i)=>btn(`0${i+1}`,'step',i,`step-tab ${i===lessonStep?'selected':''}`)).join('')}</div><span class="eyebrow">${lessonStep+1} / ${l.steps.length}</span><h2>${step[0]}</h2><p class="lesson-body">${step[1]}</p>${l.id==='right'?`<div class="pairs">${[0,2,4,6].map(i=>`<span>${techniques[i].name} / ${techniques[i+1].name}<small>${techniques[i].finger}</small></span>`).join('')}</div>`:''}${l.id==='movement'?`<div class="term-chips">${terms.filter(t=>t.category==='走手').map(t=>btn(t.name,'term',t.id,'chip')).join('')}</div>`:''}<div class="lesson-controls">${lessonStep<2?btn(`下一步 ${icon('arrow')}`,'step',lessonStep+1,'button primary'):btn(`读完了，试一试 ${icon('arrow')}`,'finish-lesson',l.id,'button primary')}</div>${sourceLinks(l.source)}</section><section class="panel example-panel"><span class="small-label">随课拆解 · 点击下面的部件</span><div class="example-glyph">${glyph(e.code,e.text)}</div>${anatomy(e,activePart,state.support)}${qinDiagram(e)}</section></div>`;}
function explore(){const e=examples[explorerIndex];return `${topHeading('一字一解 · NOTATION EXPLORER','拆开一个谱字','认出全字，再看它在减字谱里的样子。')}${btn(`${icon('search')} 查指法字典 ↓`,'dictionary','','button secondary dictionary-shortcut')}<div class="explorer-layout"><section class="panel explorer-main"><div class="panel-top"><label class="small-label" for="example-select">选择谱字</label><select id="example-select">${examples.map((x,i)=>`<option value="${i}" ${i===explorerIndex?'selected':''}>${x.text}</option>`).join('')}</select></div><div class="explorer-symbol">${glyph(e.code,e.text)}<span class="vertical-note">${e.mode}</span></div><div class="explorer-plain">${e.text}</div>${anatomy(e,activePart,state.support)}${qinDiagram(e)}<p class="explain-sentence">${describe(e)}</p><p class="caption">教学字形示例；实际谱本可能有异写或省略。</p>${sourceLinks(['font','notes'])}</section><section class="dictionary panel"><span class="eyebrow">随手查字</span><h2>指法小字典</h2><label class="searchbox">${icon('search')}<input id="term-search" type="search" placeholder="搜汉字、拼音或含义" aria-label="搜索指法" value="${esc(query)}"></label><div class="filters">${['全部','右手','左手','音色','走手','收藏'].map(x=>btn(x,'filter',x,`filter ${termFilter===x?'active':''}`)).join('')}</div><div id="term-results">${termResults()}</div></section></div>`;}
function normalized(x){return x.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();}
function termResults(){const matches=terms.filter(t=>(termFilter==='全部'||(termFilter==='收藏'?state.bookmarks.includes(t.id):t.category===termFilter))&&normalized(t.name+t.pinyin+t.definition+t.en+t.detail+translate(t.definition,'en')+translate(t.detail,'en')).includes(normalized(query)));return matches.length?matches.map(t=>`<button class="term-row" data-action="term" data-value="${t.id}"><span class="term-char">${t.name}</span><span><strong>${t.category}${state.support?` · ${esc(t.pinyin)}`:''}</strong><small>${t.definition}</small></span><span class="term-arrow">↗</span></button>`).join(''):'<p class="empty-message">没有找到。试试「猱」、nao 或「中指」。</p>';}
function openTerm(id){const t=terms.find(t=>t.id===id);if(!t)return;document.querySelector('dialog')?.remove();const dlg=document.createElement('dialog');dlg.className='term-dialog';dlg.innerHTML=`<div class="dialog-top"><span class="small-label">${t.category} · 全字与谱形</span><button class="close-dialog" aria-label="关闭">×</button></div><div class="term-dialog-glyph">${glyph(t.category==='右手'?`0${t.code}5`:t.code,t.name)}</div><h2>${t.name} <small>${esc(t.pinyin)}</small></h2><p class="english">${esc(t.en)}</p><p>${t.definition}</p><p class="muted">${t.detail}</p>${t.category==='右手'?'<p class="caption">上方用「散音、五弦」组合展示该指法。</p>':''}<div class="dialog-actions">${btn(`${icon('bookmark')} ${state.bookmarks.includes(t.id)?'取消收藏':'加入收藏'}`,'bookmark',t.id,'button secondary')}</div>${sourceLinks([t.source])}`;document.body.append(dlg);dlg.querySelector('.close-dialog').onclick=()=>dlg.close();dlg.addEventListener('click',e=>{if(e.target===dlg)dlg.close();const button=e.target.closest('[data-action="bookmark"]');if(button){state.bookmarks=state.bookmarks.includes(t.id)?state.bookmarks.filter(x=>x!==t.id):[...state.bookmarks,t.id];save();button.innerHTML=`${icon('bookmark')} ${state.bookmarks.includes(t.id)?'取消收藏':'加入收藏'}`;localize(button);}});dlg.addEventListener('close',()=>{dlg.remove();if(route()[0]==='explore')refreshTerms();});localize(dlg);dlg.showModal();}
function practice(){if(!session){const rec=recommendation(state),s=stats(state),due=Object.values(s).filter(x=>x.dueNow);return `${topHeading('主动回忆 · DAILY PRACTICE','把看懂，变成记得。','先自己判断，再看解释。每一次练习，都让下一次更有针对性。')}<div class="practice-start panel"><span class="practice-emblem">习</span><h2>八题，一小步</h2><p>根据已读课程与答题记录选题，穿插薄弱概念。<br>没有倒计时，慢慢读。</p>${btn(`开始今日练习 ${icon('arrow')}`,'start','','button primary')}<span class="caption">${due.length?`${due.length} 个概念已到复习时间`:'做过的题会在之后安排复习'}</span></div><div class="practice-options"><div><h3>已有基础？</h3><p>跨六课做一次混合自测，找出需要巩固的地方。</p>${btn('混合自测 →','diagnostic','','text-button')}</div><div><h3>把字连成句</h3><p>练习保留前文的手指、弦序与音色信息。</p>${link('进入短句练习 →','phrases','text-button')}</div></div>`;}
 if(session.index>=session.items.length){const n=session.results.length,ok=session.results.filter(a=>a.correct&&!a.assisted).length,weak=[...new Set(session.results.filter(a=>!a.correct||a.assisted).map(a=>questionMap[a.question].concept))];return `${topHeading('练习完成 · WELL PRACTICED','今天，又读懂了一点。')}<section class="panel session-summary"><div class="summary-score">${ok}<span> / ${n}</span></div><h2>独立答对</h2><p>${weak.length?'下一次，我们会再看看这些概念。':'本轮表现不错。间隔一段时间再回忆，让记忆更稳。'}</p><div class="term-chips">${weak.map(id=>`<span class="chip">${concepts[id]}</span>`).join('')}</div><div class="summary-actions">${link('查看学习记录','progress','button primary')}${btn('再练一组','start','','button secondary')}</div><p class="caption">提示后的正确答案记作辅助练习，不计入独立答对。</p></section>`;}
 const q=session.items[session.index],e=q.example?examples.find(e=>e.id===q.example):null;const hasAnswer=session.answer!==null;return `<div class="practice-top"><a href="#practice" data-action="exit-practice" class="quiet-link">${icon('back')} 暂停练习</a><span>第 ${session.index+1} / ${session.items.length} 题</span><span class="badge">${concepts[q.concept]}</span></div><div class="session-bar"><span style="width:${session.index/session.items.length*100}%"></span></div><section class="question-panel"><span class="eyebrow">${session.diagnostic?'混合自测':'独立辨读'}</span><h1>${q.prompt}</h1><div class="question-glyphs">${q.codes?q.codes.map(c=>glyph(c,'上下文谱字')).join(''):e?glyph(e.code,'待辨读谱字'):q.code?glyph(q.code,'待辨读指法'): '<div class="text-emblem">谱</div>'}</div><div class="answers">${q.options.map((answer,i)=>`<button class="answer ${hasAnswer?(answer===q.answer?'correct':session.answer===answer?'incorrect':'dim'):''}" data-action="answer" data-value="${esc(answer)}" ${hasAnswer?'disabled':''}><span class="answer-number">${i+1}</span><span>${esc(answer)}</span>${hasAnswer&&answer===q.answer?icon('check'):''}</button>`).join('')}</div>${!hasAnswer?`<div class="hint-row">${btn(session.assisted?'已使用提示':'需要一点提示？','hint','','text-button')}${session.assisted?`<p class="hint-text">${esc(q.hint||hintFor(q,e))}</p>`:''}</div>`:`<div class="feedback ${session.answer===q.answer?'success':'retry'}" role="status"><strong>${session.answer===q.answer?(session.assisted?'提示后答对 · 再独立读一次':'读对了'):'再看一眼这个部件'}</strong><p>${esc(q.explanation)}</p>${btn(`${session.index+1===session.items.length?'查看本轮小结':'下一题'} ${icon('arrow')}`,'next','','button primary')}</div>`}</section>`;}
function hintFor(q,e){if(e){if(q.concept==='string')return '弦序跟右手指法一起读。不要把左手旁的徽位数字当作弦序。';if(q.concept==='left')return '先看左手部件：名是无名指，大是大指。';if(q.concept==='hui')return '先找左手指法，再读它旁边的位置数字。七六在本课中可能是七徽六分。';if(q.concept==='mode')return '散表示空弦；泛表示轻触取泛音。普通按音字会标手指与徽位。';}return '回忆课程中的结构与前文信息，再比较选项。';}
function startSession(options={}){const items=makeSession(state,options);session={items,index:0,answer:null,assisted:false,results:[],diagnostic:!!options.diagnostic};navigate('practice');}
function phrasePage(){const p=phrases[phraseIndex];const note=p.notes[noteIndex];const e=note.example?examples.find(x=>x.id===note.example):note;return `${topHeading('连字成句 · PHRASE READER','前一字，也在下一字里。','原创读谱练习，未指定节奏；在你的琴课中应用这些读谱方法。')}<div class="phrase-chooser">${phrases.map((x,i)=>btn(x.title,'phrase',i,`chip ${i===phraseIndex?'selected':''}`)).join('')}</div><section class="panel phrase-panel"><div class="panel-top"><div><span class="eyebrow">${p.title}</span><p>${p.subtitle}</p></div>${btn(phraseStudy?'切换到自测':'切换到学习','phrase-mode','','button secondary')}</div><p class="caption">本页按从左到右阅读 · 古谱也常见自上而下、由右至左的列式排版</p><p class="caption swipe-hint">左右滑动看谱字，或用下方「下一字」。</p><div class="phrase-notes" aria-label="短句谱字">${p.notes.map((n,i)=>{const ex=n.example?examples.find(x=>x.id===n.example):n;return `<button class="phrase-note ${i===noteIndex?'selected':''}" data-action="note" data-value="${i}" aria-label="第 ${i+1} 个谱字" aria-pressed="${i===noteIndex}"><span class="small-label">0${i+1}</span>${glyph(ex.code,'谱字 '+(i+1))}${phraseStudy?`<small>${esc(ex.text||n.label)}</small>`:''}</button>`;}).join('')}</div><div class="phrase-detail" aria-live="polite">${phraseStudy||phraseReveal?`<h2>${esc(e.text||note.label)}</h2><p>${esc(note.explanation||describe(e))}</p>${e.string?qinDiagram(e):''}`:`<h2>先在心里说出这个动作。</h2><p>它使用哪根弦？前面的音色或手指信息是否仍有效？</p>${btn('揭示解释，自行核对','phrase-reveal','','button secondary')}`}</div><div class="phrase-controls">${btn('← 前一字','note',Math.max(0,noteIndex-1),'button secondary')}${btn(noteIndex===p.notes.length-1?'回到第一字 ↺':'下一字 →','note',(noteIndex+1)%p.notes.length,'button primary')}</div><p class="caption">本页的揭示与自查不计为客观答题成绩。想记录掌握情况，请做「前后文」练习。</p>${btn('练习前后文 →','start-concept','context','text-button')}${sourceLinks(p.source)}</section>`;}
function progress(){const ss=stats(state),rows=Object.values(ss).filter(s=>s.attempts),ind=state.attempts.filter(a=>!a.assisted),mastered=rows.filter(s=>s.mastered).length,rec=recommendation(state);return `${topHeading('学习留下的痕迹 · YOUR PROGRESS','让薄弱处，有迹可循。','独立回答、辅助练习与复习时间分开记录。掌握程度只是练习估计。')}<div class="progress-totals"><div><strong>${state.attempts.length}</strong><span>累计作答</span></div><div><strong>${ind.length?Math.round(ind.filter(a=>a.correct).length/ind.length*100)+'%':'—'}</strong><span>独立答对率</span></div><div><strong>${mastered}</strong><span>较稳固的概念</span></div><div><strong>${state.attempts.filter(a=>a.assisted).length}</strong><span>使用提示</span></div></div>${rows.length?`<div class="recommendation-box"><span class="eyebrow">建议下一步</span><h2>${rec.type==='review'?concepts[rec.concept]:lessonById(rec.lesson).title}</h2><p>${rec.reason}</p>${rec.type==='review'?btn('针对练习 →','start-concept',rec.concept,'button primary'):link('继续课程 →',`learn/${rec.lesson}`,'button primary')}</div><section class="panel concept-table"><div class="table-header"><h2>概念地图</h2><span class="caption">按需巩固 · 点击即可练习</span></div>${Object.values(ss).sort((a,b)=>Number(!!b.attempts)-Number(!!a.attempts)||a.score-b.score).map(s=>`<button class="concept-row" data-action="start-concept" data-value="${s.id}"><span><strong>${concepts[s.id]}</strong><small>${s.attempts?`${s.correct} 次独立答对 / ${s.attempts} 次尝试`:'尚未练习'}</small></span><span class="mastery-bar"><i style="width:${s.score}%"></i></span><span class="status-label">${!s.attempts?'未开始':s.dueNow?'待复习':s.mastered?'较稳固':'巩固中'}</span>${icon('arrow')}</button>`).join('')}</section>`:`<div class="empty-state panel"><span class="text-emblem">知</span><h2>先留下一次练习。</h2><p>你的概念地图会从真实答题记录开始，不预设分数。</p>${btn('开始混合自测','diagnostic','','button primary')}</div>`}<section class="section"><h2>给下一堂琴课留个问题</h2><label for="teacher-notes" class="muted">记录谱本异写、老师的说法，或自己卡住的地方。仅作个人笔记，不参与自动排课。</label><textarea id="teacher-notes" rows="4" maxlength="5000" placeholder="例如：老师的谱里，擘写作劈；下次问一下这个走手的处理。">${esc(state.notes)}</textarea>${btn('保存笔记','save-notes','','button secondary')}</section>`;}
function settings(){return `${topHeading('此处留存 · SETTINGS','简单，也安心。','无需登录。课程、练习记录与笔记只保存在此浏览器。')}<div class="settings-list panel"><section><h2>界面语言</h2><p>中文与英文可随时切换。谱字保留原样，学习进度共用。</p>${languageButton()}</section><section><h2>阅读辅助</h2><p>默认中文。需要时显示拼音和英文；点击字典中的任何词条都能查看读音。</p>${btn(state.support?'关闭拼音 / English':'开启拼音 / English','support','','button secondary')}</section><section><h2>给进度留一份备份</h2><p>清理浏览器数据、隐私模式或更换网址可能让记录不可用。导出文件可手动迁移到另一台设备。</p><div class="settings-buttons">${btn(`${icon('download')} 导出进度`,'export','','button primary')}<label class="button secondary" for="import-file">导入备份</label><input type="file" id="import-file" accept="application/json,.json" class="visually-hidden"></div>${storageBlocked?btn('导出无法读取的原始记录','export-raw','','text-button'):''}<p class="caption">导入前会显示记录数量，并由你选择是否合并。网站不会上传文件。</p></section><section><h2>资料与方法</h2><p>查看课程的来源、字体授权，以及复习建议如何产生。</p>${link('查看参考资料 →','sources','quiet-link')}</section></div>`;}
function sourcesPage(){return `${topHeading('有据可查 · SOURCES & METHOD','读谱有出处，学习有方法。','教学文字与练习由本站编写；资料链接便于你与老师核对。')}<div class="sources-list">${sources.map(s=>`<a class="source-card" href="${s.url}" target="_blank" rel="noopener noreferrer"><span class="eyebrow">${esc(s.name)}</span><h2>${esc(s.title)} ↗</h2><p>${esc(s.note)}</p></a>`).join('')}</div><section class="panel method-copy"><h2>复习如何调整？</h2><p>每题只把结果归到它真正检查的概念。答错或使用提示，会让该概念优先出现；独立答对后，复习间隔逐步延长为 1、3、7、14、30 天。答错后的到期时间是 10 分钟，提示后答对是 1 小时；你也可以随时主动练习。</p><p>初始顺序依据课程；已有练习记录后，系统优先处理到期与薄弱概念，并尽量穿插不同题型。独立答对增加熟悉度，连续答对和题目覆盖共同决定「较稳固」标记。这是透明的学习辅助估计，不是古琴水平考试。</p><h2>内容边界</h2><p>本站练习现代常见减字谱的基本读法。不同谱本与流派的用字、指法细节、徽位写法可能不同。遇到差异，请以所学谱本的说明及老师指导为准。原创短句用于识谱，没有声称复原某首古曲，也没有为传统谱字编造唯一的节奏。</p><h2>字体致谢</h2><p>JianZiPu © Nancy Liang / Nellodee LLC，基于 TW-Kai。使用未修改字体，遵循 SIL Open Font License 1.1。</p><a href="/assets/LICENSE.font.txt" target="_blank">查看完整字体许可 ↗</a></section>`;}
function render(){const [page='home',id]=route();let content,tab=page;if(page==='learn')content=learn(id);else if(page==='explore')content=explore();else if(page==='practice')content=practice();else if(page==='progress')content=progress();else if(page==='phrases'){content=phrasePage();tab='practice';}else if(page==='settings')content=settings();else if(page==='sources')content=sourcesPage();else{content=home();tab='home';}app.innerHTML=shell(content,tab);localize(document.body);const strip=document.querySelector('.phrase-notes'),selected=strip?.querySelector('.selected');if(selected&&strip.scrollWidth>strip.clientWidth)strip.scrollLeft=selected.offsetLeft-(strip.clientWidth-selected.offsetWidth)/2;document.title=`${getLanguage()==='en'?'Guqin Reader':'琴读'} · ${translate(({home:'今日',learn:'课程',practice:'练习',explore:'谱字字典',progress:'学习进度',phrases:'短句读谱',settings:'设置',sources:'资料与方法'})[page]||'Guqin Reader')}`;}
function download(data,name){const blob=new Blob([data],{type:'application/json'}),url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function previewImport(candidate){importCandidate=candidate;document.querySelector('dialog')?.remove();const d=document.createElement('dialog');d.className='term-dialog';d.innerHTML=`<h2>合并这份学习记录？</h2><p>备份含 ${candidate.attempts.length} 次作答、${candidate.completed.length} 堂已读课程。重复记录只保留一次。现有笔记保留；若现有笔记为空，则使用备份笔记。</p><div class="dialog-actions"><button class="button secondary" id="cancel-import">取消</button><button class="button primary" id="confirm-import">合并记录</button></div>`;document.body.append(d);d.querySelector('#cancel-import').onclick=()=>d.close();d.querySelector('#confirm-import').onclick=()=>{state=mergeState(state,importCandidate);if(!state.notes)state.notes=importCandidate.notes;storageBlocked=false;save(true);d.close();toast('已合并学习记录。');render();};d.addEventListener('close',()=>{importCandidate=null;d.remove();});localize(d);d.showModal();}
app.addEventListener('click',event=>{const target=event.target.closest('[data-action]');if(!target)return;const {action,value}=target.dataset;
 if(action==='language'){const draft=document.querySelector('#teacher-notes')?.value;const inSettings=!!target.closest('.settings-list');setLanguage(getLanguage()==='en'?'zh':'en');render();if(draft!==undefined)document.querySelector('#teacher-notes').value=draft;document.querySelector(inSettings?'.settings-list [data-action=language]':'.topbar [data-action=language]').focus({preventScroll:true});}
 else if(action==='support'){state.support=!state.support;save();render();}
 else if(action==='part'){activePart=value;render();}
 else if(action==='step'){lessonStep=Number(value);render();}
 else if(action==='finish-lesson'){state.completed=[...new Set([...state.completed,value])];save();startSession({lesson:value});}
 else if(action==='start')startSession();
 else if(action==='start-concept')startSession({concept:value});
 else if(action==='diagnostic')startSession({diagnostic:true});
 else if(action==='exit-practice'){event.preventDefault();session=null;render();}
 else if(action==='hint'&&session&&session.answer===null){session.assisted=true;render();}
 else if(action==='answer'&&session&&session.answer===null){const q=session.items[session.index];if(!q.options.includes(value))return;session.answer=value;const result={question:q.id,correct:value===q.answer,assisted:session.assisted};session.results.push(result);state=record(state,q.id,result.correct,result.assisted);save();render();}
 else if(action==='next'&&session&&session.answer!==null){session.index++;session.answer=null;session.assisted=false;render();document.querySelector('.question-panel h1, .page-heading h1')?.scrollIntoView({block:'nearest'});}
 else if(action==='filter'){termFilter=value;render();}
 else if(action==='dictionary'){document.querySelector('.dictionary').scrollIntoView({block:'start',behavior:'instant'});document.querySelector('#term-search').focus({preventScroll:true});}
 else if(action==='term')openTerm(value);
 else if(action==='phrase'){phraseIndex=Number(value);noteIndex=0;phraseReveal=false;render();}
 else if(action==='note'){noteIndex=Number(value);phraseReveal=false;render();}
 else if(action==='phrase-mode'){phraseStudy=!phraseStudy;phraseReveal=false;render();}
 else if(action==='phrase-reveal'){phraseReveal=true;render();}
 else if(action==='save-notes'){state.notes=document.querySelector('#teacher-notes').value;save();toast(storageProblem||'已保存，留到下一堂琴课。');}
 else if(action==='export'){download(JSON.stringify(state,null,2),`guqin-reader-${new Date().toISOString().slice(0,10)}.json`);toast('备份已导出。');}
 else if(action==='export-raw'){try{download(localStorage.getItem(STORAGE_KEY)||'','guqin-reader-recovery.json');}catch{toast('浏览器拒绝读取原始记录。');}}
});
function refreshTerms(){const results=document.querySelector('#term-results');results.innerHTML=termResults();localize(results);}
app.addEventListener('input',event=>{if(event.target.id==='term-search'){query=event.target.value;refreshTerms();}});
app.addEventListener('change',async event=>{if(event.target.id==='example-select'){explorerIndex=Number(event.target.value);activePart='left';render();}if(event.target.id==='import-file'){const file=event.target.files[0];if(!file)return;if(file.size>5*1024*1024){toast('备份过大，最大支持 5 MB。');return;}try{previewImport(validateState(JSON.parse(await file.text())));}catch(err){toast(err.message||'无法读取备份。原有记录没有改变。');}event.target.value='';}});
window.addEventListener('hashchange',()=>{lessonStep=0;activePart='left';render();window.scrollTo(0,0);document.querySelector('#main').focus({preventScroll:true});});
window.addEventListener('storage',event=>{if(event.key===STORAGE_KEY&&event.newValue){try{state=mergeState(state,validateState(JSON.parse(event.newValue)));if(!session||route()[0]!=='practice')render();}catch{toast('另一个窗口的进度格式不受支持。');}}});
render();
